run:
  timeout: 5m

linters:
  enable-all: true

  disable:
    # Pure insanity
    - exhaustruct
    - forbidigo
    - depguard
    - perfsprint
    - prealloc
    - containedctx

    # We're not interested in formatting/sorting imports more than "go fmt" would do
    - gci
    - gofumpt
    - goimports

    # We're not a publicly available package, so it's OK to have dynamic errors
    - err113

    # We will control this ourselves
    - varnamelen
    - mnd
    - paralleltest

    # What else we're supposed to return if we've operated on an interface from the beginning?
    - ireturn

    # False positives
    - wsl
    - wrapcheck
    - tagliatelle

    # Deprecated linters
    - tenv

linters-settings:
  funlen:
    lines: 110

  cyclop:
    max-complexity: 14

  gosec:
    excludes:
      - G115

issues:
  exclude-dirs:
    - internal/server/httprange
  exclude-rules:
    - path: internal/command/
      linters:
        # It's OK to use global variables for github.com/spf13/cobra commands
        - gochecknoglobals
    - path: internal/version/
      linters:
        # It's OK to use global variables for automatically settings versions through GoReleaser
        - gochecknoglobals
        # It's OK to use an init() function to automatically calculate the FullVersion, which needs
        # to be a variable
        - gochecknoinits
    - path: internal/server/.*_test.go
      linters:
        - noctx
        - funlen
