project_name: chacha

before:
  hooks:
    - go mod download

builds:
  - main: cmd/main.go
    ldflags: >
      -X github.com/cirruslabs/chacha/internal/version.Version={{.Version}}
      -X github.com/cirruslabs/chacha/internal/version.Commit={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: binary
    format: binary
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
  - id: regular
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"

release:
  prerelease: auto

brews:
  - name: chacha
    ids:
      - regular
    repository:
      owner: cirruslabs
      name: homebrew-cli
    license: FSL-1.1-Apache-2.0
    caveats: See the Github repository for more information

nfpms:
  - package_name: chacha
    vendor: Cirrus Labs, Inc.
    homepage: https://github.com/cirruslabs/chacha
    maintainer: support@cirruslabs.org
    description: Caching proxy for Cirrus Runners
    license: FSL-1.1-Apache-2.0
    section: misc
    formats:
      - deb
      - rpm

furies:
  - account: cirruslabs

notarize:
  macos:
    - enabled: '{{ isEnvSet "MACOS_SIGN_P12" }}'
      sign:
        certificate: "{{.Env.MACOS_SIGN_P12}}"
        password: "{{.Env.MACOS_SIGN_PASSWORD}}"
      notarize:
        issuer_id: "{{.Env.MACOS_NOTARY_ISSUER_ID}}"
        key_id: "{{.Env.MACOS_NOTARY_KEY_ID}}"
        key: "{{.Env.MACOS_NOTARY_KEY}}"
